### PR TITLE
Use phootwork/file from master that fix PHP7 problems

### PR DESCRIPTION
**Pull request by Nas1k**
Problem with class phootwork/lang/String

### CODE REVIEW

**Comment by gossi** [comment]
Hey @Nas1k can you tell me, what are you trying to repair? At the moment I cannot accept this PR as it would change this package and as such the one on packagist as well. However, I'm here to help fixing your issue with you.

**Comment by gossi** [comment]
Seems like, the php-code-generator is broken because of the phootwork/file package, which - when I release a new version - would work again?

**Comment by Nas1k** [comment]
@gossi Yes it's correct. When are you planning release new version for phootwork/file? Thanks.

**Comment by gossi** [comment]
done.

**Pull request closed without merging**
