### PR TITLE
Handle types as Map of objects, auto add use statements, and some utility methods

### LINKED ISSUE #66: Features adding suggestion
Hi,

I have some ideas if you approve of i will create a PR for it : 
 - handle types by adding a `PhpType` interface that will be implemented by `PhpClass` and `PhpInterface` classes to be able to automatically add use statements
- `PhpMethod` and `PhpParameter` type  will be list of types merged from typehint and docblock (if we set multiple types we will use only doc block)
- `PhpClass getInterfaces` return collection of `PhpInterface` objects
- Auto add use statement when adding an interface to `PhpClass`

What do you think of this ?

Cheers,

### PR DESCRIPTION
**Pull request by sidux**
Resolves : #66 

**feature**: handle types as Map of PhpType instead of string (it will take into account typehints and phpdoc types, merge both if conflict)
**feature**: auto add use statement if PhpTypeInterface used as type (for methods, properties and parameters type)
**feature**: add methods to get the objects for traits, interface, parent class
**refacto**: rename setMethod, setProperty to addMethod, addProperty
**fix** : fix the getNullable return value is not bool error

Hi, here is the list of features i was talking about in the issue, this is only to test the logic and i don't expect it to be merged as it is, since it needs more coverage and some changes and it depends if you wan't to keep the backward compatibility or not.

Take a look at this and i will be happy to discuss more about it.

### CODE REVIEW

**Comment by gossi** [comment]
I only fly over the changes. There is a lot of stuff going on, that I want to address properly and I need your help with this. I cannot map code changes to the features you described here. Can you split this PR into smaller ones? At best I'd ask you to make separate PRs, one for each feature + bugfix. I see there might be interdependencies between them, in that case can you figure out a smart way to do that? (Main idea: code for one PR goes with one mentioned feature).

Second, what I can already tell you, the methods: `setMethod()` and `setProperty()` will stay as is. That is, because you cannot add two methods or props with the same name 😉 Simply: `$cls->setProperty(PhpProperty::create('foo'))->setProperty(PhpProperty::create('foo'))` is nonsense. The semantics for those methods names is: Set this _one_ named property ... and by that be careful with naming it properly. Hope the explanation helps.

**Comment by gossi** [comment]
I see five different pull requests in here:

- 3x feature additions
- 1x refactor
- 1x fix

Please split your PR into these five. From that massive code changes it is impossible to map the code change to one of the things mentioned here and by that impossible to review.

**Comment by sidux** [comment]
@gossi sorry i won't have time to work in this PR again, features i added here are pretty opinionated I will keep them only in my fork. So im closing this, thx for your time and sorry for the inconvenience.

**Comment by gossi** [comment]
Ok. Sorry, couldn't give them more of an understanding here. Happy to help out in the future. Maybe to also handle such custom modifications we can think about an extension API, so you can plug-in your changes?

**Comment by sidux** [comment]
It might help but i guess thats not crucial, i managed to get everything i need with some inheritance and some helpers

**Pull request closed without merging**
