### PR TITLE
Bump dependencies and parser refactor

### PR DESCRIPTION
**Pull request by cristianoc72**
- Bump php to 8+ versio
- Bump dependencies
- Refactor the parser for compatibility with the new `nikic/php-parser` version. Now the parser infers the types firstly from the code and then from the docblock

By now, tests are not green and there could be some code style errors.

### CODE REVIEW

**Comment by cristianoc72** [comment]
@gossi I'm back from vacation and I start again to work on our libraries.

I'ld like to know your opinion about libraries namespace:
1. continue with `gossi` namespace (`gossi\docblock`, `gossi\php-code-generato` etc.)
2. change to `phpowermove` (`phpowermove\docblock`, `phpowermove\php-code-generator` etc.)

If we change the namespace, we should update packagist, too.

**Comment by gossi** [comment]
I think makes more sense to use the new namespace. Usually as an end User you use the package name and copy it to github.com/<copypasta> to reach for the repo. That's a nice "ui" to it, which I think is valuable to have.

Feel free to change them all.

Do they restart as v1? Or do they continue with their current version number? 🤔

**Comment by cristianoc72** [comment]
Imho we should continue to the current version number. Namespace change introduce a bc break so we should bump to the next major version.
On Packagist, it could be nice to have `gossi/docblock` for current version (so that a user can continue with it since he'll decide to update both version and namespace) and `phpowermove/docblock` starting from next version. I don't know if it's possible and how. Anyway, we'll write this change in the documentation.

**Comment by gossi** [comment]
Yeah, makes sense. Go for it.

On packagist, you can mark a package "abandonned" and set the successor to it. That's what packagist is offering. Dunno if they "announce" it on the cli, when running the install command.

**Comment by cristianoc72** [comment]
> Yeah, makes sense. Go for it.
> [cut]
> Dunno if they "announce" it on the cli, when running the install command.
Yes, they do.

I'm gonna close this PR: I'll re-submit it later, after changing the namespace. I started the update of the first library https://github.com/phpowermove/docblock/pull/18
:crossed_fingers:

**Pull request closed without merging**
